
# config.toml
base_url = "https://marieaurelielapierre.com"
theme = "kodama-theme"
compile_sass = true
build_search_index = true


title = "Marie Aurélie Lapierre"

[markdown]
highlight_code = true


[translations]
Biography = "Biography"
Interests = "Interests"
Education = "Education"
toc = "Table of Contents"
Published = "Published"
Abstract = "Abstract"
volume = "volume"
number = "number"
pages = "pages"

[extra]

# Image of your avatar displayed on the landing page
avatar = "static/img/lapierre_1.jpg"
# Image of the favicon
favicon = "static/img/lapierre_2.jpg"

# Your email address showed in the contact section
email = "lapierre@gate.cnrs.fr"

# If you don't want to show your contact information in the index
contact_in_index = false

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
#  { path = "#contacts", name = "Contact" },
# {path = "#", name= "Bio"},
{path = "CV/cv_aurelie.pdf", name="CV" }
]